language: python
env:
  - PYTHON_VERSION=2.7 IPYTHON_KERNEL=python2
  - PYTHON_VERSION=3.6 IPYTHON_KERNEL=python3
  - PYTHON_VERSION=3.7 IPYTHON_KERNEL=python3

before_install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - sh Miniconda3-latest-Linux-x86_64.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
  - conda create -n testenv --yes -c conda-forge python=$PYTHON_VERSION pip numpy scipy matplotlib
  - source activate testenv
  - conda install --yes -c conda-forge pygrib scikit-learn scikit-image netcdf4 basemap
  - pip install arrow
  - pip install pytest
  - pip install .
script:
  - py.test
notifications:
  email: true